# Generated by Django 5.2.5 on 2025-08-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="facade_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="restaurant_facades/",
                verbose_name="Фото фасада",
            ),
        ),
    ]
