# Generated by Django 5.2.5 on 2025-09-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_reservation_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Имя")),
                ("phone", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=150)),
                ("subject", models.CharField(max_length=150)),
                ("message", models.CharField(max_length=150)),
            ],
        ),
    ]
