# Generated by Django 5.2.5 on 2025-09-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_dishcategory_dish"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="dish",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="dish",
            name="ingredients",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Ингредиенты"
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="slug",
            field=models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
        ),
    ]
